service: campfire

image: smallbets/campfire

servers:
  web:
    - <%= ENV.fetch("SERVER_IP") %>

proxy:
  ssl: true
  host: <%= ENV.fetch("PROXY_HOST") %>
  app_port: 3000

registry:
  username: <%= ENV.fetch("REGISTRY_USERNAME") %>

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    DISABLE_SSL: "true"
    RAILS_ENV: "production"

  secret:
    - APP_VERSION
    - LAST_DEPLOY
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_DEFAULT_REGION
    - RESEND_API_KEY
    - VIMEO_ACCESS_TOKEN
    - GUMROAD_ACCESS_TOKEN
    - GUMROAD_ON
    - GUMROAD_PRODUCT_IDS
    - WEBHOOK_SECRET
    - COOKIE_DOMAIN

volumes:
  - "/disk/campfire/:/rails/storage/"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
