#!/bin/bash
cd /home/campfire
export filename=campfire-$(date +%Y-%m-%d-%H-%M).tar
tar -cvf $filename /home/campfire/storage/
aws s3 cp $filename s3://smallbets/backups/campfire/$filename
rm $filename